# This file was generated by SquareLine Studio
# SquareLine Studio version: SquareLine Studio 1.5.3
# LVGL version: 9.1.0
# Project name: SquareLine_Project

import lvgl as lv
import fs_driver
import task_handler
import machine
import time
from cst816s import CST816S, GESTURE_NONE, GESTURE_SWIPE_LEFT, GESTURE_SWIPE_RIGHT, GESTURE_SWIPE_UP, GESTURE_SWIPE_DOWN, GESTURE_SINGLE_CLICK, GESTURE_DOUBLE_CLICK, GESTURE_LONG_PRESS

# 初始化显示
try:
    from display_driver import init_display
    display = init_display()
    display.init()
    print("Display initialized successfully")
except Exception as e:
    print(f"Display initialization failed: {e}")

# 初始化触摸控制器
def init_touch():
    """初始化CST816S触摸控制器"""
    try:
        # 根据您的硬件配置调整I2C引脚
        i2c = machine.I2C(0, scl=machine.Pin(6), sda=machine.Pin(7), freq=400000)
        
        touch = CST816S(
            device=i2c,
            reset_pin=machine.Pin(5, machine.Pin.OUT),
            debug=True
        )
        
        # 配置触摸参数
        touch.auto_sleep = False  # 禁用自动休眠以获得更快的响应
        touch.set_long_press_time(2)  # 设置长按时间为2秒
        touch.enable_double_click(True)  # 启用双击检测
        
        print("Touch controller initialized successfully")
        touch.print_debug_info()
        
        return touch
    except Exception as e:
        print(f"Touch initialization failed: {e}")
        return None

# 初始化触摸
touch = init_touch()

# 获取默认显示并设置主题
dispp = lv.display_get_default()
theme = lv.theme_default_init(dispp, lv.palette_main(lv.PALETTE.BLUE), lv.palette_main(lv.PALETTE.RED), False, lv.font_default())
dispp.set_theme(theme)

class GestureHandler:
    """手势处理类 - 集成到SquareLine项目"""
    def __init__(self, touch_controller):
        self.touch = touch_controller
        self.last_gesture_check = time.ticks_ms()
        self.gesture_handlers = {}
        self.current_screen = None
        self.keyboard_visible = True
        
    def register_gesture_handler(self, gesture, handler):
        """注册手势处理器"""
        self.gesture_handlers[gesture] = handler
        
    def set_current_screen(self, screen):
        """设置当前屏幕"""
        self.current_screen = screen
        
    def check_gestures(self):
        """检查并处理手势"""
        if self.touch is None:
            return
            
        current_time = time.ticks_ms()
        if time.ticks_diff(current_time, self.last_gesture_check) > 100:  # 每100ms检查一次
            gesture = self.touch.get_gesture()
            if gesture != GESTURE_NONE:
                gesture_name = self.touch.gesture_to_string(gesture)
                print(f"Detected gesture: {gesture_name}")
                
                # 调用注册的手势处理器
                if gesture in self.gesture_handlers:
                    self.gesture_handlers[gesture]()
                else:
                    # 默认手势处理
                    self._handle_default_gesture(gesture)
            
            self.last_gesture_check = current_time
    
    def _handle_default_gesture(self, gesture):
        """默认手势处理"""
        if gesture == GESTURE_SWIPE_LEFT:
            print("Swipe left - navigating back")
        elif gesture == GESTURE_SWIPE_RIGHT:
            print("Swipe right - navigating forward")
        elif gesture == GESTURE_SWIPE_UP:
            print("Swipe up - scrolling up")
        elif gesture == GESTURE_SWIPE_DOWN:
            print("Swipe down - scrolling down")
        elif gesture == GESTURE_SINGLE_CLICK:
            print("Single click - select")
        elif gesture == GESTURE_DOUBLE_CLICK:
            print("Double click - quick action")
        elif gesture == GESTURE_LONG_PRESS:
            print("Long press - context menu")

# 创建手势处理器
gesture_handler = GestureHandler(touch) if touch else None

def ui_theme_set(idx):
   return

def SetFlag( obj, flag, value):
    if (value):
        obj.add_flag(flag)
    else:
        obj.remove_flag(flag)
    return

_ui_comp_table = {}
_ui_comp_prev = None
_ui_name_prev = None
_ui_child_prev = None
_ui_comp_table.clear()

def _ui_comp_del_event(e):
    target = e.get_target()
    _ui_comp_table[id(target)].remove()

def ui_comp_get_child(comp, child_name):
    return _ui_comp_table[id(comp)][child_name]

def ui_comp_get_root_from_child(child, compname):
    for component in _ui_comp_table:
        if _ui_comp_table[component]["_CompName"]==compname:
            for part in _ui_comp_table[component]:
                if id(_ui_comp_table[component][part]) == id(child):
                    return _ui_comp_table[component]
    return None

def SetBarProperty(target, id, val):
   if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
   if id == 'Value': target.set_value(val, lv.ANIM.OFF)
   return

def SetPanelProperty(target, id, val):
   if id == 'Position_X': target.set_x(val)
   if id == 'Position_Y': target.set_y(val)
   if id == 'Width': target.set_width(val)
   if id == 'Height': target.set_height(val)
   return

def SetDropdownProperty(target, id, val):
   if id == 'Selected':
      target.set_selected(val)
   return

def SetImageProperty(target, id, val, val2):
   if id == 'Image': target.set_src(val)
   if id == 'Angle': target.set_rotation(val2)
   if id == 'Zoom': target.set_scale(val2)
   return

def SetLabelProperty(target, id, val):
   if id == 'Text': target.set_text(val)
   return

def SetRollerProperty(target, id, val):
   if id == 'Selected':
      target.set_selected(val, lv.ANIM.OFF)
   if id == 'Selected_with_anim':
      target.set_selected(val, lv.ANIM.ON)
   return

def SetSliderProperty(target, id, val):
   if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
   if id == 'Value': target.set_value(val, lv.ANIM.OFF)
   return

def ChangeScreen( src, fademode, speed, delay):
    print("Change screen to: "+str([name for name in globals() if globals()[name] is src]))
    lv.screen_load_anim(src, fademode, speed, delay, False)
    if gesture_handler:
        gesture_handler.set_current_screen(src)
    return

def DeleteScreen(src):
    return

def IncrementArc( trg, val):
    trg.set_value(trg.get_value()+val)
    trg.send_event(lv.EVENT.VALUE_CHANGED, None)
    return

def IncrementBar( trg, val, anim):
    trg.set_value(trg.get_value()+val,anim)
    return

def IncrementSlider( trg, val, anim):
    trg.set_value(trg.get_value()+val,anim)
    trg.send_event(lv.EVENT.VALUE_CHANGED, None)
    return

def KeyboardSetTarget( keyboard, textarea):
    keyboard.set_textarea(textarea)
    return

def ModifyFlag( obj, flag, value):
    if (value=="TOGGLE"):
        if ( obj.has_flag(flag) ):
            obj.remove_flag(flag)
        else:
            obj.add_flag(flag)
        return

    if (value=="ADD"):
        obj.add_flag(flag)
    else:
        obj.remove_flag(flag)
    return

def ModifyState( obj, state, value):
    if (value=="TOGGLE"):
        if ( obj.has_state(state) ):
            obj.remove_state(state)
        else:
            obj.add_state(state)
        return

    if (value=="ADD"):
        obj.add_state(state)
    else:
        obj.remove_state(state)
    return

def TextAreaMoveCursor( trg, val):
    if val=="UP" : trg.cursor_up()
    if val=="RIGHT" : trg.cursor_right()
    if val=="DOWN" : trg.cursor_down()
    if val=="LEFT" : trg.cursor_left()
    trg.add_state(lv.STATE.FOCUSED)
    return

def set_opacity(obj, v):
    obj.set_style_opa(v, lv.STATE.DEFAULT|lv.PART.MAIN)
    return

def SetTextValueArc( trg, src, prefix, postfix):
    trg.set_text(prefix+str(src.get_value())+postfix)
    return

def SetTextValueSlider( trg, src, prefix, postfix):
    trg.set_text(prefix+str(src.get_value())+postfix)
    return

def SetTextValueChecked( trg, src, txton, txtoff):
    if src.has_state(lv.STATE.CHECKED):
        trg.set_text(txton)
    else:
        trg.set_text(txtoff)
    return

def StepSpinbox( trg, val):
    if val==1 : trg.increment()
    if val==-1 : trg.decrement()
    trg.send_event(lv.EVENT.VALUE_CHANGED, None)
    return

def SwitchTheme(val):
    ui_theme_set(val)
    return

# COMPONENTS

 # COMPONENT Label6
def ui_Label6_create(comp_parent):
    cui_Label6 = lv.label(comp_parent)
    cui_Label6.set_text("C")
    cui_Label6.set_width(lv.SIZE_CONTENT)	# 1
    cui_Label6.set_height(lv.SIZE_CONTENT)   # 1
    cui_Label6.set_x(-93)
    cui_Label6.set_y(-4)
    cui_Label6.set_align( lv.ALIGN.CENTER)
    cui_Label6.set_style_text_decor( lv.TEXT_DECOR.NONE, lv.PART.MAIN | lv.STATE.DEFAULT )
    _ui_comp_table[id(cui_Label6)]= {"Label6" : cui_Label6, "_CompName" : "Label6"}
    return cui_Label6

ui____initial_actions0 = lv.obj()

ui_Screen1 = lv.obj()
SetFlag(ui_Screen1, lv.obj.FLAG.SCROLLABLE, False)

ui_TextArea1 = lv.textarea(ui_Screen1)
ui_TextArea1.set_width(150)
ui_TextArea1.set_height(70)
ui_TextArea1.set_placeholder_text("Placeholder...")
ui_TextArea1.set_x(40)
ui_TextArea1.set_y(20)
ui_TextArea1.set_align( lv.ALIGN.CENTER)

ui_Keyboard1 = lv.keyboard(ui_Screen1)
ui_Keyboard1.set_width(200)
ui_Keyboard1.set_height(100)
ui_Keyboard1.set_x(0)
ui_Keyboard1.set_y(28)
ui_Keyboard1.set_align( lv.ALIGN.CENTER)

# 设置键盘和文本区域的关联
ui_Keyboard1.set_textarea(ui_TextArea1)

# 创建手势状态显示标签
ui_GestureStatus = lv.label(ui_Screen1)
ui_GestureStatus.set_text("Gesture: Ready")
ui_GestureStatus.set_width(180)
ui_GestureStatus.set_height(30)
ui_GestureStatus.set_x(0)
ui_GestureStatus.set_y(80)
ui_GestureStatus.set_align(lv.ALIGN.CENTER)
ui_GestureStatus.set_style_bg_color(lv.color_hex(0x404040), 0)
ui_GestureStatus.set_style_bg_opa(lv.OPA._50, 0)
ui_GestureStatus.set_style_text_align(lv.TEXT_ALIGN.CENTER, 0)
ui_GestureStatus.set_style_pad_all(5, 0)


# 注册手势处理函数
if gesture_handler:
    gesture_handler.set_current_screen(ui_Screen1)
    
    def toggle_keyboard():
        """切换键盘显示状态"""
        if gesture_handler.keyboard_visible:
            ui_Keyboard1.add_flag(lv.obj.FLAG.HIDDEN)
            ui_GestureStatus.set_text("Keyboard Hidden")
            ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.RED), 0)
        else:
            ui_Keyboard1.clear_flag(lv.obj.FLAG.HIDDEN)
            ui_GestureStatus.set_text("Keyboard Shown")
            ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.GREEN), 0)
        gesture_handler.keyboard_visible = not gesture_handler.keyboard_visible
    
    def on_swipe_left():
        """左滑手势处理 - 隐藏键盘"""
        ui_GestureStatus.set_text("Swipe Left - Hide Keyboard")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.ORANGE), 0)
        if gesture_handler.keyboard_visible:
            toggle_keyboard()
    
    def on_swipe_right():
        """右滑手势处理 - 显示键盘"""
        ui_GestureStatus.set_text("Swipe Right - Show Keyboard")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.BLUE), 0)
        if not gesture_handler.keyboard_visible:
            toggle_keyboard()
    
    def on_swipe_up():
        """上滑手势处理 - 清除文本"""
        ui_GestureStatus.set_text("Swipe Up - Clear Text")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.TEAL), 0)
        ui_TextArea1.set_text("")
    
    def on_swipe_down():
        """下滑手势处理 - 添加示例文本"""
        ui_GestureStatus.set_text("Swipe Down - Add Text")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.PURPLE), 0)
        current_text = ui_TextArea1.get_text()
        ui_TextArea1.set_text(current_text + "Hello ")
    
    def on_single_click():
        """单击手势处理 - 聚焦文本区域"""
        ui_GestureStatus.set_text("Single Click - Focus")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.GREEN), 0)
        ui_TextArea1.add_state(lv.STATE.FOCUSED)
        if not gesture_handler.keyboard_visible:
            toggle_keyboard()  # 自动显示键盘
    
    def on_double_click():
        """双击手势处理 - 清除所有文本"""
        ui_GestureStatus.set_text("Double Click - Clear All")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.YELLOW), 0)
        ui_TextArea1.set_text("")
    
    def on_long_press():
        """长按手势处理 - 特殊功能"""
        ui_GestureStatus.set_text("Long Press - Special")
        ui_GestureStatus.set_style_bg_color(lv.palette_main(lv.PALETTE.RED), 0)
        # 长按可以用于触发特殊功能，比如显示系统信息
        current_text = ui_TextArea1.get_text()
        ui_TextArea1.set_text("Long press detected!\n" + current_text)
    
    # 注册手势处理器
    gesture_handler.register_gesture_handler(GESTURE_SWIPE_LEFT, on_swipe_left)
    gesture_handler.register_gesture_handler(GESTURE_SWIPE_RIGHT, on_swipe_right)
    gesture_handler.register_gesture_handler(GESTURE_SWIPE_UP, on_swipe_up)
    gesture_handler.register_gesture_handler(GESTURE_SWIPE_DOWN, on_swipe_down)
    gesture_handler.register_gesture_handler(GESTURE_SINGLE_CLICK, on_single_click)
    gesture_handler.register_gesture_handler(GESTURE_DOUBLE_CLICK, on_double_click)
    gesture_handler.register_gesture_handler(GESTURE_LONG_PRESS, on_long_press)

# 加载屏幕
lv.screen_load(ui_Screen1)

class TouchTaskHandler:
    """触摸任务处理类"""
    def __init__(self, gesture_handler):
        self.gesture_handler = gesture_handler
        self.last_update = time.ticks_ms()
    
    def update(self):
        """更新触摸状态"""
        current_time = time.ticks_ms()
        
        # 每50ms更新一次手势检测（不影响LVGL的主循环性能）
        if time.ticks_diff(current_time, self.last_update) > 50:
            if self.gesture_handler:
                self.gesture_handler.check_gestures()
            self.last_update = current_time

# 创建任务处理器
try:
    th = task_handler.TaskHandler()
    touch_task_handler = TouchTaskHandler(gesture_handler)
    
    # 添加触摸更新到主循环
    def touch_update_task():
        """触摸更新任务"""
        touch_task_handler.update()
    
    # 注册定时任务
    try:
        th.add_periodic_task(50, touch_update_task)  # 每50ms检查一次手势
        print("Touch gesture handler registered successfully")
    except Exception as e:
        print(f"Periodic task registration failed: {e}")
except Exception as e:
    print(f"Task handler initialization failed: {e}")

print("SquareLine Project with CST816S gestures is ready!")
print("Gesture controls:")
print("- Swipe Left: Hide keyboard")
print("- Swipe Right: Show keyboard") 
print("- Swipe Up: Clear text")
print("- Swipe Down: Add text")
print("- Single Click: Focus text area")
print("- Double Click: Clear all text")
print("- Long Press: Special function")
