# This file was generated by SquareLine Studio
# SquareLine Studio version: 1.5.3
# LVGL version: 9.1.0
# Project name: SquareLine_Project

import lvgl as lv
import fs_driver
from display_driver import init_display
import task_handler
import math  # Added for trigonometric calculations
import sys
import urequests
import json
import time
import network
import ntptime
from machine import RTC
import gc9a01

# Initialize WiFi
sta_if = network.WLAN(network.STA_IF)
sta_if.active(False)
SSID = "xxx"  # Replace with your WiFi SSID
PASSWORD = "xxx"  # Replace with your WiFi Password
city = "changzhou" # Replace with your city
weather_dict = {'0@1x.png':'Sunny','1@1x.png':'Clear','2@1x.png':'Fair',
                '3@1x.png':'Fair','4@1x.png':'Cloudy','5@1x.png':'Partly Cloudy',
                '6@1x.png':'Partly Cloudy','7@1x.png':'Mostly Cloudy','8@1x.png':'Mostly Cloudy',
                '9@1x.png':'Overcast','10@1x.png':'Shower','11@1x.png':'Thundershower',
                '12@1x.png':'Thundershower with Hail','13@1x.png':'Light Rain','14@1x.png':'Moderate Rain',
                '15@1x.png':'Heavy Rain','16@1x.png':'Storm','17@1x.png':'Heavy Storm',
                '18@1x.png':'Severe Storm','19@1x.png':'Ice Rain','20@1x.png':'Sleet',
                '21@1x.png':'Snow Flurry','22@1x.png':'Light Snow','23@1x.png':'Moderate Snow',
                '24@1x.png':'Heavy Snow','25@1x.png':'Snowstorm','26@1x.png':'Dust',
                '27@1x.png':'Sand','28@1x.png':'Duststorm','29@1x.png':'Sandstorm',
                '30@1x.png':'Foggy','31@1x.png':'Haze','32@1x.png':'Windy',
                '33@1x.png':'Blustery','34@1x.png':'Hurricane','35@1x.png':'Tropical Storm',
                '36@1x.png':'Tornado','37@1x.png':'Cold','38@1x.png':'Hot',
                '99@1x.png':'Unknown'}

weather_url = f"https://api.seniverse.com/v3/weather/now.json?key=S9hoa4Wza9Hcs2uX_&location={city}&language=en&unit=c"

# Global variables for tracking previous time state
prev_seconds = -1
prev_minutes = -1
prev_hours = -1

def find_keys_by_value(my_dict, target_value):
    return [key for key, value in my_dict.items() if value == target_value]

def fetchWeather():
    try:
        result = urequests.get(weather_url)
        return result.text
    except Exception as e:
        print("Weather fetch error:", e)
        return None

def connect_wifi():
    if not sta_if.isconnected():
        print("Connecting to WiFi...")
        sta_if.active(True)
        sta_if.connect(SSID, PASSWORD)
        max_wait = 10
        while max_wait > 0:
            if sta_if.isconnected():
                print("WiFi Connected. IP:", sta_if.ifconfig()[0])
                return True
            max_wait -= 1
            time.sleep(1)
        print("WiFi Connection Failed")
        return False
    return True

# Initialize LVGL
lv.init()

# Initialize display using the driver module
display = init_display()
display.set_power(False)
display.init()
display.set_color_inversion(True)
display.set_rotation(lv.DISPLAY_ROTATION._0)
display.set_backlight(10)

# Initialize RTC
rtc = RTC()

scr = lv.screen_active()
scr.set_style_bg_color(lv.color_hex(0xFFFFFF), 0)  # Black background

# --- SquareLine Studio Functions ---
def ui_theme_set(idx):
    return

def SetFlag(obj, flag, value):
    if value:
        obj.add_flag(flag)
    else:
        obj.remove_flag(flag)
    return

_ui_comp_table = {}
_ui_comp_prev = None
_ui_name_prev = None
_ui_child_prev = None
_ui_comp_table.clear()

def _ui_comp_del_event(e):
    target = e.get_target()
    _ui_comp_table[id(target)].remove()

def ui_comp_get_child(comp, child_name):
    return _ui_comp_table[id(comp)][child_name]

def ui_comp_get_root_from_child(child, compname):
    for component in _ui_comp_table:
        if _ui_comp_table[component]["_CompName"] == compname:
            for part in _ui_comp_table[component]:
                if id(_ui_comp_table[component][part]) == id(child):
                    return _ui_comp_table[component]
    return None

def SetBarProperty(target, id, val):
    if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
    if id == 'Value': target.set_value(val, lv.ANIM.OFF)
    return

def SetPanelProperty(target, id, val):
    if id == 'Position_X': target.set_x(val)
    if id == 'Position_Y': target.set_y(val)
    if id == 'Width': target.set_width(val)
    if id == 'Height': target.set_height(val)
    return

def SetDropdownProperty(target, id, val):
    if id == 'Selected':
        target.set_selected(val)
    return

def SetImageProperty(target, id, val, val2):
    if id == 'Image': target.set_src(val)
    if id == 'Angle': target.set_rotation(val2)

def SetLabelProperty(target, id, val):
    if id == 'Text': target.set_text(val)
    return

def SetRollerProperty(target, id, val):
    if id == 'Selected':
        target.set_selected(val, lv.ANIM.OFF)
    if id == 'Selected_with_anim':
        target.set_selected(val, lv.ANIM.ON)
    return

def SetSliderProperty(target, id, val):
    if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
    if id == 'Value': target.set_value(val, lv.ANIM.OFF)
    return

def ChangeScreen(src, fademode, speed, delay):
    print("Change screen to: " + str([name for name in globals() if globals()[name] is src]))
    lv.screen_load_anim(src, fademode, speed, delay, False)
    return

def DeleteScreen(src):
    return

def IncrementArc(trg, val):
    trg.set_value(trg.get_value() + val)
    trg.send_event(lv.EVENT.VALUE_CHANGED, None)
    return

def IncrementBar(trg, val, anim):
    trg.set_value(trg.get_value() + val, anim)
    return

def IncrementSlider(trg, val, anim):
    trg.set_value(trg.get_value() + val, anim)
    trg.send_event(lv.EVENT.VALUE_CHANGED, None)
    return

def KeyboardSetTarget(keyboard, textarea):
    keyboard.set_textarea(textarea)
    return

def ModifyFlag(obj, flag, value):
    if value == "TOGGLE":
        if obj.has_flag(flag):
            obj.remove_flag(flag)
        else:
            obj.add_flag(flag)
        return
    if value == "ADD":
        obj.add_flag(flag)
    else:
        obj.remove_flag(flag)
    return

def ModifyState(obj, state, value):
    if value == "TOGGLE":
        if obj.has_state(state):
            obj.remove_state(state)
        else:
            obj.add_state(state)
        return
    if value == "ADD":
        obj.add_state(state)
    else:
        obj.remove_state(state)
    return

def TextAreaMoveCursor(trg, val):
    if val == "UP": trg.cursor_up()
    if val == "RIGHT": trg.cursor_right()
    if val == "DOWN": trg.cursor_down()
    if val == "LEFT": trg.cursor_left()
    trg.add_state(lv.STATE.FOCUSED)
    return

def set_opacity(obj, v):
    obj.set_style_opa(v, lv.STATE.DEFAULT | lv.PART.MAIN)
    return

def SetTextValueArc(trg, src, prefix, postfix):
    trg.set_text(prefix + str(src.get_value()) + postfix)
    return

def SetTextValueSlider(trg, src, prefix, postfix):
    trg.set_text(prefix + str(src.get_value()) + postfix)
    return

def SetTextValueChecked(trg, src, txton, txtoff):
    if src.has_state(lv.STATE.CHECKED):
        trg.set_text(txton)
    else:
        trg.set_text(txtoff)
    return

def StepSpinbox(trg, val):
    if val == 1: trg.increment()
    if val == -1: trg.decrement()
    trg.send_event(lv.EVENT.VALUE_CHANGED, None)
    return

def SwitchTheme(val):
    ui_theme_set(val)
    return

# --- Clock Update Function ---
def update_clock():
    global prev_seconds, prev_minutes, prev_hours
    
    current_time = rtc.datetime()
    hours = current_time[4]
    minutes = current_time[5]
    seconds = current_time[6]
    
    # Only update if time has changed to avoid unnecessary redraws
    time_changed = False
    
    if seconds != prev_seconds:
        # Update second hand
        update_second_hand(seconds)
        prev_seconds = seconds
        time_changed = True
    
    if minutes != prev_minutes:
        # Update minute hand
        update_minute_hand(minutes, seconds)
        prev_minutes = minutes
        time_changed = True
    
    if hours != prev_hours:
        # Update hour hand
        update_hour_hand(hours, minutes)
        prev_hours = hours
        time_changed = True
    
    # Update digital time display only when needed
    if time_changed:
        time_str = "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
        ui_Label2.set_text(time_str)
        
        # Update date only once per minute to reduce load
        if seconds == 0:
            date_str = "{:04d}-{:02d}-{:02d}".format(current_time[0], current_time[1], current_time[2])
            ui_Label3.set_text(date_str)

def update_second_hand(seconds):
    angle_deg = seconds * 6  # 6 degrees per second
    angle_rad = math.radians(angle_deg)
    clock_radius = 100
    center_x, center_y = 120, 120
    
    # Calculate start point slightly inside the arc
    start_radius = clock_radius - 15
    start_x = center_x + start_radius * math.sin(angle_rad)
    start_y = center_y - start_radius * math.cos(angle_rad)
    
    # Calculate end point at the edge of the arc
    end_x = center_x + clock_radius * math.sin(angle_rad)
    end_y = center_y - clock_radius * math.cos(angle_rad)
    
    ui_SecondHand.set_points([{"x": int(start_x), "y": int(start_y)}, {"x": int(end_x), "y": int(end_y)}], 2)

def update_minute_hand(minutes, seconds):
    # Include seconds for smooth minute hand movement
    total_minutes = minutes + seconds / 60.0
    angle_deg = total_minutes * 6  # 6 degrees per minute
    angle_rad = math.radians(angle_deg)
    clock_radius = 85  # Shorter than second hand
    center_x, center_y = 120, 120
    
    start_x = center_x + 20 * math.sin(angle_rad)
    start_y = center_y - 20 * math.cos(angle_rad)
    end_x = center_x + clock_radius * math.sin(angle_rad)
    end_y = center_y - clock_radius * math.cos(angle_rad)
    
    ui_MinuteHand.set_points([{"x": int(start_x), "y": int(start_y)}, {"x": int(end_x), "y": int(end_y)}], 2)

def update_hour_hand(hours, minutes):
    # Convert to 12-hour format and include minutes for smooth hour hand movement
    hours_12 = hours % 12
    total_hours = hours_12 + minutes / 60.0
    angle_deg = total_hours * 30  # 30 degrees per hour
    angle_rad = math.radians(angle_deg)
    clock_radius = 60  # Shortest hand
    center_x, center_y = 120, 120
    
    start_x = center_x + 15 * math.sin(angle_rad)
    start_y = center_y - 15 * math.cos(angle_rad)
    end_x = center_x + clock_radius * math.sin(angle_rad)
    end_y = center_y - clock_radius * math.cos(angle_rad)
    
    ui_HourHand.set_points([{"x": int(start_x), "y": int(start_y)}, {"x": int(end_x), "y": int(end_y)}], 2)

# --- NTP Sync Function ---
def sync_ntp_time(e):
    if not sta_if.isconnected():
        ui_Label4.set_text("WiFi not connected")
        return
    ui_Label4.set_text("Syncing...")
    lv.task_handler()
    try:
        ntptime.settime()
        ui_Label4.set_text("Sync OK!")
        # Reset previous time values to force update
        global prev_seconds, prev_minutes, prev_hours
        prev_seconds = prev_minutes = prev_hours = -1
    except Exception as e:
        ui_Label4.set_text("Sync Failed")
        print("NTP Error:", e)

# --- Weather Update Timer Callback ---
def update_weather(e):
    if connect_wifi():
        weather_data = fetchWeather()
        if weather_data:
            try:
                weather_json = json.loads(weather_data)
                wheather = weather_json["results"][0]["now"]["text"]
                temp = weather_json["results"][0]["now"]["temperature"]
                weather_image_keys = find_keys_by_value(weather_dict, wheather)
                weather_image_key = weather_image_keys[0] if weather_image_keys else '99@1x.png'
                
                # Update temperature label
                ui_label.set_text(f"{temp}°C")
                # Update weather label
                ui_label5.set_text(wheather)
                
                # Update weather image
                try:
                    with open(f'weather_incons/{weather_image_key}', 'rb') as f:
                        png_data = f.read()
                    img_cogwheel_argb = lv.image_dsc_t({
                        'data_size': len(png_data),
                        'data': png_data
                    })
                    img1.set_src(img_cogwheel_argb)
                except Exception as e:
                    print(f"Could not load weather icon {weather_image_key}: {e}")
            except Exception as e:
                print(f"Weather JSON parse error: {e}")
                ui_label.set_text("Weather Parse Error")
        else:
            ui_label.set_text("Weather Fetch Failed")
    else:
        ui_label.set_text("WiFi Not Connected")

# --- Components ---
# Connect to WiFi at startup
connect_wifi()

ui_Screen1 = lv.obj()
SetFlag(ui_Screen1, lv.obj.FLAG.SCROLLABLE, False)

# Create an image from the png file
weather_data = fetchWeather()
if weather_data:
    try:
        weather_json = json.loads(weather_data)
        wheather = weather_json["results"][0]["now"]["text"]
        temp = weather_json["results"][0]["now"]["temperature"]
        weather_image_keys = find_keys_by_value(weather_dict, wheather)
        weather_image_key = weather_image_keys[0] if weather_image_keys else '99@1x.png'
    except:
        weather_image_key = '99@1x.png'
        temp = "N/A"
        wheather = "Unknown"
else:
    weather_image_key = '99@1x.png'
    temp = "N/A"
    wheather = "Unknown"

# Hour Hand (shortest and thickest)
ui_HourHand = lv.line(ui_Screen1)
ui_HourHand.set_points([{"x": 120, "y": 120}, {"x": 120, "y": 60}], 1)
ui_HourHand.set_style_line_color(lv.color_hex(0x800080), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_HourHand.set_style_line_width(8, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_HourHand.set_style_line_rounded(True, lv.PART.MAIN | lv.STATE.DEFAULT)

# Minute Hand (medium length and thickness)
ui_MinuteHand = lv.line(ui_Screen1)
ui_MinuteHand.set_points([{"x": 120, "y": 120}, {"x": 120, "y": 35}], 1)
ui_MinuteHand.set_style_line_color(lv.color_hex(0xFFA500), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_MinuteHand.set_style_line_width(4, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_MinuteHand.set_style_line_rounded(True, lv.PART.MAIN | lv.STATE.DEFAULT)

# Second Hand (longest and thinnest)
ui_SecondHand = lv.line(ui_Screen1)
ui_SecondHand.set_points([{"x": 120, "y": 120}, {"x": 120, "y": 20}], 1)
ui_SecondHand.set_style_line_color(lv.color_hex(0x39FF14), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_SecondHand.set_style_line_width(2, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_SecondHand.set_style_line_rounded(True, lv.PART.MAIN | lv.STATE.DEFAULT)

# Center dot for clock hands
ui_CenterDot = lv.obj(ui_Screen1)
ui_CenterDot.set_size(8, 8)
ui_CenterDot.set_pos(116, 116)  # Center at (120, 120) with 4px offset for 8px circle
ui_CenterDot.set_style_bg_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_CenterDot.set_style_border_width(0, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_CenterDot.set_style_radius(4, lv.PART.MAIN | lv.STATE.DEFAULT)
SetFlag(ui_CenterDot, lv.obj.FLAG.SCROLLABLE, False)

try:
    with open(f'weather_incons/{weather_image_key}', 'rb') as f:
        png_data = f.read()
    img_cogwheel_argb = lv.image_dsc_t({
        'data_size': len(png_data),
        'data': png_data
    })
except:
    print(f"Could not find weather_incons/{weather_image_key}")
    # Create a fallback image or handle the error appropriately
    img_cogwheel_argb = None

img1 = lv.image(ui_Screen1)
if img_cogwheel_argb:
    img1.set_src(img_cogwheel_argb)
img1.align(lv.ALIGN.CENTER, 0, -70)
img1.set_size(80, 80)

ui_Arc1 = lv.arc(ui_Screen1)
ui_Arc1.set_width(240)
ui_Arc1.set_height(240)
ui_Arc1.set_align(lv.ALIGN.CENTER)
ui_Arc1.set_range(0, 360)
ui_Arc1.set_value(360)
ui_Arc1.set_bg_angles(110, 70)
ui_Arc1.set_style_arc_color(lv.color_hex(0x070707), lv.PART.INDICATOR | lv.STATE.DEFAULT)
ui_Arc1.set_style_arc_opa(255, lv.PART.INDICATOR | lv.STATE.DEFAULT)

# Add clock markings
for i in range(60):
    angle_deg = i * 6  # 6 degrees per minute
    angle_rad = math.radians(angle_deg)
    center_x, center_y = 120, 120
    
    # Hour marks (every 5 minutes) are longer
    if i % 5 == 0:
        # Outer point
        outer_x = center_x + 120 * math.sin(angle_rad)
        outer_y = center_y - 120 * math.cos(angle_rad)
        # Inner point (shorter for hour marks)
        inner_x = center_x + 100 * math.sin(angle_rad)
        inner_y = center_y - 100 * math.cos(angle_rad)
        line_width = 3
    else:
        # Minute marks are shorter
        outer_x = center_x + 120 * math.sin(angle_rad)
        outer_y = center_y - 120 * math.cos(angle_rad)
        inner_x = center_x + 110 * math.sin(angle_rad)
        inner_y = center_y - 110 * math.cos(angle_rad)
        line_width = 1
    
    # Create the line for the mark
    mark = lv.line(ui_Screen1)
    mark.set_points([{"x": int(inner_x), "y": int(inner_y)}, 
                    {"x": int(outer_x), "y": int(outer_y)}], 2)
    mark.set_style_line_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT)
    mark.set_style_line_width(line_width, lv.PART.MAIN | lv.STATE.DEFAULT)

ui_Label2 = lv.label(ui_Screen1)
ui_Label2.set_text("12:00:00")  # Initial time
ui_Label2.set_width(lv.SIZE_CONTENT)
ui_Label2.set_height(lv.SIZE_CONTENT)
ui_Label2.set_x(0)
ui_Label2.set_y(60)
ui_Label2.set_align(lv.ALIGN.CENTER)
ui_Label2.set_style_text_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label2.set_style_text_opa(255, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label2.set_style_text_font(lv.font_montserrat_16, lv.PART.MAIN | lv.STATE.DEFAULT)

ui_Label3 = lv.label(ui_Screen1)
ui_Label3.set_text("2025-07-08")  # Initial date
ui_Label3.set_width(lv.SIZE_CONTENT)
ui_Label3.set_height(lv.SIZE_CONTENT)
ui_Label3.set_x(0)
ui_Label3.set_y(40)
ui_Label3.set_align(lv.ALIGN.CENTER)
ui_Label3.set_style_text_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label3.set_style_text_opa(255, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label3.set_style_text_font(lv.font_montserrat_16, lv.PART.MAIN | lv.STATE.DEFAULT)



# NTP Sync Button
ui_Button1 = lv.button(ui_Screen1)
ui_Button1.set_width(100)
ui_Button1.set_height(40)
ui_Button1.set_align(lv.ALIGN.BOTTOM_MID)
ui_Label4 = lv.label(ui_Button1)
ui_Label4.set_text(f"{city}")
ui_Label4.set_align(lv.ALIGN.CENTER)
ui_Button1.add_event_cb(sync_ntp_time, lv.EVENT.CLICKED, None)

# Create temp on the screen
ui_label = lv.label(ui_Screen1)
ui_label.set_text(f"{temp}°C")
ui_label.set_style_text_color(lv.color_hex(0x00FF00), 0)
ui_label.align(lv.ALIGN.CENTER, 0, -15)

# Create weather on the screen
ui_label5 = lv.label(ui_Screen1)
ui_label5.set_text(wheather)
ui_label5.set_style_text_color(lv.color_hex(0xFFFF00), 0)
ui_label5.align(lv.ALIGN.CENTER, 0, -35)

lv.screen_load(ui_Screen1)

# --- Create Timers ---
# Clock update timer - runs every 100ms for smooth updates
clock_timer = lv.timer_create(lambda e: update_clock(), 100, None)

# Weather update timer - 3 hours = 10,800,000 milliseconds
weather_timer = lv.timer_create(update_weather, 10800000, None)

# Run weather update immediately on startup
update_weather(None)

# Initialize clock display
update_clock()

th = task_handler.TaskHandler()

# --- Main Loop ---
while True:
    lv.tick_inc(5)
    lv.task_handler()
    time.sleep_ms(5)
