# This file was generated by SquareLine Studio
# SquareLine Studio version: SquareLine Studio 1.5.3
# LVGL version: 9.2.2
# Project name: SquareLine_Project_watch

import lvgl as lv
import fs_driver
from display_driver import init_display
import task_handler
import math
import sys
import urequests
import json
import time
import network
import ntptime
import machine
from machine import Pin, RTC
import gc9a01
from cst816s import CST816S, GESTURE_SWIPE_LEFT, GESTURE_SWIPE_RIGHT

# ===== CONFIGURATION =====
SSID = "Prefoco"
PASSWORD = "18961210318" 
city = "changzhou"
weather_url = f"https://api.seniverse.com/v3/weather/now.json?key=S9hoa4Wza9Hcs2uX_&location={city}&language=zh-Hans&unit=c"

# ===== GLOBAL VARIABLES =====
sta_if = network.WLAN(network.STA_IF)
prev_seconds = prev_minutes = prev_hours = -1
current_screen_idx = 0
screens = []

last_swipe_time = 0
swipe_cooldown = 500  # ms，滑动切换冷却时间
# ===== WEATHER DICTIONARY (commented out as not used) =====
'''
weather_dict = {'0@1x.png':'晴','1@1x.png':'晴','2@1x.png':'晴',
              '3@1x.png':'晴','4@1x.png':'多云','5@1x.png':'晴间多云',
              '6@1x.png':'晴间多云','7@1x.png':'大部多云','8@1x.png':'大部多云',
              '9@1x.png':'阴','10@1x.png':'阵雨','11@1x.png':'雷阵雨',
              '12@1x.png':'雷阵雨伴有冰雹','13@1x.png':'小雨','14@1x.png':'中雨',
              '15@1x.png':'大雨','16@1x.png':'暴雨','17@1x.png':'大暴雨',
              '18@1x.png':'特大暴雨','19@1x.png':'冻雨','20@1x.png':'雨夹雪',
              '21@1x.png':'阵雪','22@1x.png':'小雪','23@1x.png':'中雪',
              '24@1x.png':'大雪','25@1x.png':'暴雪','26@1x.png':'浮尘',
              '27@1x.png':'扬沙','28@1x.png':'沙尘暴','29@1x.png':'强沙尘暴',
              '30@1x.png':'雾','31@1x.png':'霾','32@1x.png':'风',
              '33@1x.png':'大风','34@1x.png':'飓风','35@1x.png':'热带风暴',
              '36@1x.png':'龙卷风','37@1x.png':'冷','38@1x.png':'热',
              '99@1x.png':'未知'}
'''

# ===== NETWORK FUNCTIONS =====
def connect_wifi():
    if not sta_if.isconnected():
        print("Connecting to WiFi...")
        sta_if.active(True)
        sta_if.connect(SSID, PASSWORD)
        max_wait = 10
        while max_wait > 0:
            if sta_if.isconnected():
                print("WiFi Connected. IP:", sta_if.ifconfig()[0])
                return True
            max_wait -= 1
            time.sleep(1)
        print("WiFi Connection Failed")
        return False
    return True

def fetch_weather():
    try:
        result = urequests.get(weather_url)
        print(result.text)
        return result.text
    except Exception as e:
        print("Weather fetch error:", e)
        return None

# ===== TIME FUNCTIONS =====
def update_clock():
    global prev_seconds, prev_minutes, prev_hours
    
    current_time = rtc.datetime()
    hours, minutes, seconds = current_time[4], current_time[5], current_time[6]
    
    time_changed = False
    
    if seconds != prev_seconds:
        update_second_hand(seconds)
        prev_seconds = seconds
        time_changed = True
    
    if minutes != prev_minutes:
        update_minute_hand(minutes, seconds)
        prev_minutes = minutes
        time_changed = True
    
    if hours != prev_hours:
        update_hour_hand(hours, minutes)
        prev_hours = hours
        time_changed = True
    
    if time_changed:
        time_str = "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
        ui_Label2.set_text(time_str)
        
        if seconds == 0:
            date_str = "{:02d}/{:02d}/{:02d}".format(current_time[0], current_time[1], current_time[2])
            ui_Label3.set_text(date_str)

def update_second_hand(seconds):
    angle_deg = seconds * 6
    angle_rad = math.radians(angle_deg)
    clock_radius, center_x, center_y = 100, 120, 120
    
    start_x = center_x + (clock_radius - 15) * math.sin(angle_rad)
    start_y = center_y - (clock_radius - 15) * math.cos(angle_rad)
    end_x = center_x + clock_radius * math.sin(angle_rad)
    end_y = center_y - clock_radius * math.cos(angle_rad)
    
    ui_SecondHand.set_points([{"x": int(start_x), "y": int(start_y)}, {"x": int(end_x), "y": int(end_y)}], 2)

def update_minute_hand(minutes, seconds):
    total_minutes = minutes + seconds / 60.0
    angle_deg = total_minutes * 6
    angle_rad = math.radians(angle_deg)
    clock_radius, center_x, center_y = 85, 120, 120
    
    start_x = center_x + 20 * math.sin(angle_rad)
    start_y = center_y - 20 * math.cos(angle_rad)
    end_x = center_x + clock_radius * math.sin(angle_rad)
    end_y = center_y - clock_radius * math.cos(angle_rad)
    
    ui_MinuteHand.set_points([{"x": int(start_x), "y": int(start_y)}, {"x": int(end_x), "y": int(end_y)}], 2)

def update_hour_hand(hours, minutes):
    hours_12 = hours % 12
    total_hours = hours_12 + minutes / 60.0
    angle_deg = total_hours * 30
    angle_rad = math.radians(angle_deg)
    clock_radius, center_x, center_y = 60, 120, 120
    
    start_x = center_x + 15 * math.sin(angle_rad)
    start_y = center_y - 15 * math.cos(angle_rad)
    end_x = center_x + clock_radius * math.sin(angle_rad)
    end_y = center_y - clock_radius * math.cos(angle_rad)
    
    ui_HourHand.set_points([{"x": int(start_x), "y": int(start_y)}, {"x": int(end_x), "y": int(end_y)}], 2)

def sync_ntp_time(e):
    if not sta_if.isconnected():
        ui_Label4.set_text("WiFi not connected")
        return
    ui_Label4.set_text("Syncing...")
    lv.task_handler()
    try:
        ntptime.settime()
        ui_Label4.set_text("Sync OK!")
        global prev_seconds, prev_minutes, prev_hours
        prev_seconds = prev_minutes = prev_hours = -1
    except Exception as e:
        ui_Label4.set_text("Sync Failed")
        print("NTP Error:", e)

# ===== WEATHER FUNCTIONS =====
def update_weather(e):
    if connect_wifi():
        weather_data = fetch_weather()
        if weather_data:
            try:
                weather_json = json.loads(weather_data)
                weather = weather_json["results"][0]["now"]["text"]
                temp = weather_json["results"][0]["now"]["temperature"]
                weather_image_keys = f"{weather_json['results'][0]['now']['code']}@1x.png"
                
                ui_label.set_text(f"{temp}°C")
                ui_label5.set_text(weather)
                
                try:
                    with open(f'weather_incons/{weather_image_keys}', 'rb') as f:
                        png_data = f.read()
                    img_cogwheel = lv.image_dsc_t({'data_size': len(png_data), 'data': png_data})
                    img1.set_src(img_cogwheel)
                except Exception as e:
                    print(f"Could not load weather icon {weather_image_keys}: {e}")
                    ui_label.set_text("Icon Load Error")
            except Exception as e:
                print(f"Weather JSON parse error: {e}")
                ui_label.set_text("Weather Parse Error")
        else:
            ui_label.set_text("Weather Fetch Failed")
    else:
        ui_label.set_text("WiFi Not Connected")



def switch_screen(direction):
    global current_screen_idx
    if direction == "next":
        current_screen_idx = (current_screen_idx + 1) % len(screens)
    elif direction == "prev":
        current_screen_idx = (current_screen_idx - 1) % len(screens)
    lv.screen_load(screens[current_screen_idx])

def check_gesture(*args):
    global last_swipe_time
    coords = touch._get_coords()
    now = time.ticks_ms()
    if coords is not None:
        gesture = touch.get_gesture()
        if gesture == GESTURE_SWIPE_RIGHT and time.ticks_diff(now, last_swipe_time) > swipe_cooldown:
            switch_screen("next")
            last_swipe_time = now
        elif gesture == GESTURE_SWIPE_LEFT and time.ticks_diff(now, last_swipe_time) > swipe_cooldown:
            switch_screen("prev")
            last_swipe_time = now
# ===== UI HELPER FUNCTIONS =====
def SetFlag(obj, flag, value):
    if value:
        obj.add_flag(flag)
    else:
        obj.remove_flag(flag)

def create_clock_marks():
    for i in range(60):
        angle_deg = i * 6
        angle_rad = math.radians(angle_deg)
        center_x, center_y = 120, 120
        
        if i % 5 == 0:
            outer_x = center_x + 120 * math.sin(angle_rad)
            outer_y = center_y - 120 * math.cos(angle_rad)
            inner_x = center_x + 100 * math.sin(angle_rad)
            inner_y = center_y - 100 * math.cos(angle_rad)
            line_width = 3
        else:
            outer_x = center_x + 120 * math.sin(angle_rad)
            outer_y = center_y - 120 * math.cos(angle_rad)
            inner_x = center_x + 110 * math.sin(angle_rad)
            inner_y = center_y - 110 * math.cos(angle_rad)
            line_width = 1
        
        mark = lv.line(ui_time)
        mark.set_points([{"x": int(inner_x), "y": int(inner_y)}, 
                        {"x": int(outer_x), "y": int(outer_y)}], 2)
        mark.set_style_line_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT)
        mark.set_style_line_width(line_width, lv.PART.MAIN | lv.STATE.DEFAULT)

# ===== INITIALIZATION =====
# Initialize hardware and services
sta_if.active(False)
connect_wifi()

# Initialize LVGL and display
lv.init()
display = init_display()
display.set_power(False)
display.init()
display.set_color_inversion(True)
display.set_rotation(lv.DISPLAY_ROTATION._0)
display.set_backlight(100)
i2c = machine.I2C(0, scl=machine.Pin(6), sda=machine.Pin(7), freq=400000)
touch = CST816S(i2c, reset_pin=machine.Pin(5, machine.Pin.OUT))
touch.auto_sleep = False

# Initialize RTC
rtc = RTC()

# Initialize file system and fonts
fs_drv = lv.fs_drv_t()
fs_driver.fs_register(fs_drv, 'S')
myfont = lv.binfont_create("S:myfont_18.bin")
#myfont1 = lv.binfont_create("S:ui_font_FonT2.bin")

# ===== UI CREATION =====
# Create screens
ui_time = lv.obj()
ui_weather = lv.obj()
ui_date = lv.obj()
ui_qrcode = lv.obj()

# Configure screens
for screen in [ui_time, ui_weather, ui_date, ui_qrcode]:
    screen.set_style_bg_color(lv.color_hex(0x000000), 0)
    SetFlag(screen, lv.obj.FLAG.SCROLLABLE, False)

screens = [ui_time, ui_weather, ui_date, ui_qrcode]

# Create clock face
create_clock_marks()

# Clock labels
clock_labels = [
    ("12", 0, -90), ("6", 0, 90), 
    ("3", 90, 0), ("9", -90, 0)
]

for text, x, y in clock_labels:
    label = lv.label(ui_time)
    label.set_text(text)
    label.set_size(lv.SIZE_CONTENT, lv.SIZE_CONTENT)
    label.set_x(x)
    label.set_y(y)
    label.set_align(lv.ALIGN.CENTER)
    label.set_style_text_font(lv.font_montserrat_16, lv.PART.MAIN | lv.STATE.DEFAULT)
    label.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT)

# Clock hands
ui_HourHand = lv.line(ui_time)
ui_HourHand.set_points([{"x": 120, "y": 120}, {"x": 120, "y": 60}], 1)
ui_HourHand.set_style_line_color(lv.color_hex(0x800080), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_HourHand.set_style_line_width(8, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_HourHand.set_style_line_rounded(True, lv.PART.MAIN | lv.STATE.DEFAULT)

ui_MinuteHand = lv.line(ui_time)
ui_MinuteHand.set_points([{"x": 120, "y": 120}, {"x": 120, "y": 35}], 1)
ui_MinuteHand.set_style_line_color(lv.color_hex(0xFFA500), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_MinuteHand.set_style_line_width(4, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_MinuteHand.set_style_line_rounded(True, lv.PART.MAIN | lv.STATE.DEFAULT)

ui_SecondHand = lv.line(ui_time)
ui_SecondHand.set_points([{"x": 120, "y": 120}, {"x": 120, "y": 20}], 1)
ui_SecondHand.set_style_line_color(lv.color_hex(0x39FF14), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_SecondHand.set_style_line_width(2, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_SecondHand.set_style_line_rounded(True, lv.PART.MAIN | lv.STATE.DEFAULT)

# Center dot
ui_CenterDot = lv.obj(ui_time)
ui_CenterDot.set_size(8, 8)
ui_CenterDot.set_pos(116, 116)
ui_CenterDot.set_style_bg_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_CenterDot.set_style_border_width(0, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_CenterDot.set_style_radius(4, lv.PART.MAIN | lv.STATE.DEFAULT)
SetFlag(ui_CenterDot, lv.obj.FLAG.SCROLLABLE, False)

# Weather UI components
weather_data = fetch_weather()
temp, weather, weather_image_keys = "N/A", "Unknown", '99@1x.png'
if weather_data:
    try:
        weather_json = json.loads(weather_data)
        weather = weather_json["results"][0]["now"]["text"]
        temp = weather_json["results"][0]["now"]["temperature"]
        weather_image_keys = f"{weather_json['results'][0]['now']['code']}@1x.png"
    except Exception as e:
        print(f"Initial weather JSON parse error: {e}")

try:
    with open(f'weather_incons/{weather_image_keys}', 'rb') as f:
        png_data = f.read()
    img_cogwheel_argb = lv.image_dsc_t({'data_size': len(png_data), 'data': png_data})
except:
    print(f"Could not find weather_incons/{weather_image_keys}")
    img_cogwheel_argb = None

img1 = lv.image(ui_weather)
if img_cogwheel_argb:
    img1.set_src(img_cogwheel_argb)
img1.align(lv.ALIGN.CENTER, 0, -25)
img1.set_size(58, 58)

ui_Arc1 = lv.arc(ui_weather)
ui_Arc1.set_size(240, 240)
ui_Arc1.set_align(lv.ALIGN.CENTER)
ui_Arc1.set_range(0, 360)
ui_Arc1.set_value(360)
ui_Arc1.set_bg_angles(110, 70)
ui_Arc1.set_style_arc_color(lv.color_hex(0x070707), lv.PART.INDICATOR | lv.STATE.DEFAULT)
ui_Arc1.set_style_arc_opa(255, lv.PART.INDICATOR | lv.STATE.DEFAULT)

ui_MinuteHand1 = lv.spinner(ui_weather)
ui_MinuteHand1.set_size(240, 240)
ui_MinuteHand1.set_align(lv.ALIGN.CENTER)
ui_MinuteHand1.set_style_arc_color(lv.color_hex(0xDDA3F8), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_MinuteHand1.set_style_arc_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT)
ui_MinuteHand1.set_style_arc_width(5, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_MinuteHand1.set_style_arc_color(lv.color_hex(0xAD04FB), lv.PART.INDICATOR | lv.STATE.DEFAULT)
ui_MinuteHand1.set_style_arc_opa(255, lv.PART.INDICATOR| lv.STATE.DEFAULT)
ui_MinuteHand1.set_style_arc_width(5, lv.PART.INDICATOR | lv.STATE.DEFAULT)

# NTP Sync Button
ui_Button1 = lv.button(ui_weather)
ui_Button1.set_size(100, 40)
ui_Button1.set_align(lv.ALIGN.BOTTOM_MID)
ui_Label4 = lv.label(ui_Button1)
ui_Label4.set_text("常州")
ui_Label4.set_align(lv.ALIGN.CENTER)
ui_Button1.add_event_cb(sync_ntp_time, lv.EVENT.CLICKED, None)
ui_Label4.set_style_text_font(myfont, 0)

# Weather labels
ui_label = lv.label(ui_weather)
ui_label.set_text(f"{temp}°C")
ui_label.set_style_text_color(lv.color_hex(0x00FF00), 0)
ui_label.align(lv.ALIGN.CENTER, 0, 30)
ui_label.set_style_text_font(myfont, 0)

ui_label5 = lv.label(ui_weather)
ui_label5.set_text(weather)
ui_label5.set_style_text_color(lv.color_hex(0xFFFF00), 0)
ui_label5.align(lv.ALIGN.CENTER, 0, 10)
ui_label5.set_style_text_font(myfont, 0)

# Date and time labels
ui_Label2 = lv.label(ui_date)
ui_Label2.set_text("12:00:00")
ui_Label2.set_size(lv.SIZE_CONTENT, lv.SIZE_CONTENT)
ui_Label2.set_pos(0, 20)
ui_Label2.set_align(lv.ALIGN.CENTER)
ui_Label2.set_style_text_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label2.set_style_text_opa(255, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label2.set_style_text_font(myfont, 0)

ui_Label3 = lv.label(ui_date)
ui_Label3.set_text("25/07/08")
ui_Label3.set_size(lv.SIZE_CONTENT, lv.SIZE_CONTENT)
ui_Label3.set_pos(0, -20)
ui_Label3.set_align(lv.ALIGN.CENTER)
ui_Label3.set_style_text_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label3.set_style_text_opa(255, lv.PART.MAIN | lv.STATE.DEFAULT)
ui_Label3.set_style_text_font(myfont, 0)

# QR Code
bg_color = lv.palette_lighten(lv.PALETTE.LIGHT_BLUE, 5)
fg_color = lv.palette_darken(lv.PALETTE.BLUE, 4)

qr = lv.qrcode(ui_qrcode)
qr.set_size(150)
qr.set_dark_color(fg_color)
qr.set_light_color(bg_color)
data = "https://lvgl.io"
qr.update(data, len(data))
qr.center()
qr.set_style_border_color(bg_color, 0)
qr.set_style_border_width(5, 0)

# ===== SETUP TIMERS AND EVENT HANDLERS =====
lv.screen_load(ui_time)

# Create timers
clock_timer = lv.timer_create(lambda e: update_clock(), 100, None)
weather_timer = lv.timer_create(update_weather, 10800000, None)
update_weather(None)
update_clock()



th = task_handler.TaskHandler()
th.add_event_cb(check_gesture, 50)

# ===== MAIN LOOP =====
while True:
    lv.tick_inc(5)
    lv.task_handler()
    time.sleep_ms(5)

